# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('time_register', models.DateTimeField(auto_now_add=True)),
                ('time_actualization', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
