# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios_registrado',
        ),
    ]
