# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20161011_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(blank=True, default='', null=True, upload_to='pdfs'),
        ),
    ]
